### ISSUE TITLE
How can I get  shopping cart data?

### ISSUE THREAD

**Issue by macobse** [OmarMahili/SeatchartJS#1]
I would like to the current shopping cart data like seat number, seat type and price. Is there any method 
that can return this values? I need help? Thanks  in advance

**Comment by omahili** [comment]
There is a private variable called ‘shoppingCartDict‘ which is what you need. Make it public or create a function which returns it in your local code. 

Since I think this is very useful I will create a pull request and merge it in the coming days.

**Comment by macobse** [comment]
Thanks!

**Comment by omarmahili** [comment]
#2

**Comment by omahili** [comment]
#2
