### ISSUE TITLE
[Feature Request] Support for creating irregular locations 

### ISSUE THREAD

**Issue by suguoyao** [OmarMahili/SeatchartJS#17]
Hi,
This project is very awesome! At present it seems to only support the creation of a seat element with an area of 1*1. But I have a booth selection scene that needs to create an irregular selection of locations. 

Thanks in advance.

**Comment by suguoyao** [comment]
The picture below is what I want
![image](https://user-images.githubusercontent.com/16471605/61620292-2b714100-aca3-11e9-84e4-0b079ee12c25.png)

Thanks! 😊

**Comment by omahili** [comment]
Hi @suguoyao, 
thank you, I'm happy to hear that!

So what you'd like is a section of multiple seats, so when you click it you select all of the seats into it, right?

**Comment by suguoyao** [comment]
@omarmahili 
No, I mean it is a whole seat, just like the location in the exhibition hall, not composed of multiple seats.
You can see the [demo](https://www.eiseverywhere.com/ehome/286192) that can select exhibit booth.

Thank you very much for your prompt reply😸. My english is not very good and please understand that~

**Comment by omahili** [comment]
Alright it's clear now. Don't worry your english is good 👍 

So, implementing sections as polygons would be quite hard or even impossibile with divs. 
The solution would be to port everything into a canvas or svg. With svg being simpler to implement.

Otherwise, to keep things even simpler, rectangular sections only would be the way to go.

**Comment by suguoyao** [comment]
@omarmahili 
Thanks~
I think polygons can also consist of multiple divs. It may be necessary to refactor the data structure at initialization. And of course this will become more complicated. 
Finally, I'm still looking forward to implementing this feature 😆

**Comment by omahili** [comment]
I thought about it, but it's not the optimal solution.

Right now I'm working on some other features, but I can try to implement it when I'm done.

**Comment by suguoyao** [comment]
Ok, thanks, I will keep following this project 👍👍

**Comment by suguoyao** [comment]
I think you can add the feature of creating a rectangular sections to your todo list. Hope you can accept this request 🤩

**Comment by omahili** [comment]
Sure, I will!
