### ISSUE TITLE
Mark different types of seats

### ISSUE THREAD

**Issue by ovicko** [OmarMahili/SeatchartJS#26]
I want to mark seats as VVIP, VIP and Regular to help the user know beforehand that a specific seat is VIP or regular etc.
How do I go about it?
 
Just bumped into the project and it's pretty cool man!

**Comment by ovicko** [comment]
Something like this [Screenshot](https://imgur.com/a/pbZsgj4)

**Comment by omahili** [comment]
Hi @ovicko thank you, I appreciate it!

I get what is your goal, but unfortunately it's not possible yet. 
It's on my todo list for this project and I hope to get there soon. 
I think there will be two types of configurable maps: 'static', where users do not choose the type of the seats, and 'free'.
Right now there's a feature/typescript branch which is my priority and I'm pretty close to merging it. What you're asking for comes right next this task, along with a simpler indexing method.

**Comment by omahili** [comment]
Closing as it is fixed in #39

**Comment by omahili** [comment]
Fixed in #39
