### ISSUE TITLE
Multi-User Environment Support

### ISSUE THREAD

**Issue by ventis07** [OmarMahili/SeatchartJS#3]
Hi,
This is quite a very nice job. And it already looks like a very good prospect for implementation any where as open source. But i have a few concerns. Assuming i want to integrate this to an e-commerce website, does this component have support for a multi user environment as you know multiple clients could be making an attempt to select the same seat. How does seatchartjs manage such. I havent seen anything like for instance socket.io in the project.

Am curious and would like to know your plans for that

**Comment by omahili** [comment]
Hi @ventis07,
I'm very happy to hear of your interest in the project.

For websockets support the only thing missing is a function to select/unselect/disable seats, which at the moment does not exist yet (planned for this week).

You can intercept when a user selects or unselects a seat (`onAddedSeat` and `onRemovedSeat` events) and send a message to the websocket server which will then broadcast it. When the clients receive a message (except the sender which discards it), they will change the state of their _Seatchart_ with the function mentioned above. 
Your websocket server needs to handle multiple clients trying to select the same seat. For example the first one should select the seat without problems, while the others trying to select the same one should get a message to disable the seat and notify the user of what happened.

In the future I could create an example (backend and frontend) to show simple usage with websockets.

**Comment by ventis07** [comment]
Hi,
Yes, you have started a great project and that's all good and great. And you have a good plan.For for implmentation of the websockets. Asides what you have planned to do on a small scale, please take a look at this **very old but very relevant repo** on github. https://github.com/smirea/ticketReservation. Its a very elaborate one to handle all that is required in a multi-user environment. And has all you will need for the kind of scenario i mentioned in my first post.

In case you want help, just give a shout out. I will check back your repo by this time next week on your projected planned schedule for this week. Perhaps subsequently we might be able to do something together.

Regards

**Comment by omahili** [comment]
Hi @ventis07,
I gave a look to the repository you mentioned above. I think that there's no need to embed it into this library. I prefer giving the developers the freedom of choosing any implementation they prefer. 
So I'd rather create a demo for developers in need and address them in that matter.

Besides that, if there's anything missing to make it possible, let me know, I'd be happy to help.
In the coming days I'll submit a useful PR.

**Comment by ventis07** [comment]
Hi @omarmahili,
No problem. I think the first place before we can assess if anything is missing is seeing the demo you want to showcase in this regard. As you opined in your first response. You can first showcase the major functioanilities regarding the multi user and from there we will know what is there and what is not. When are you proposing to share a useful PR and demo for the features. I will grab the branch and provide you a feedback

**Comment by omahili** [comment]
#4

**Comment by ventis07** [comment]
Hi, is the seatGap related to the multi user support. I have gone though but does not seem to fulfill what the essence of multi user is. Could you explain. How can i reach you personally?

**Comment by omahili** [comment]
> Hi, is the seatGap related to the multi user support. I have gone though but does not seem to fulfill what the essence of multi user is. Could you explain. 

@ventis07 Along with gap detection I introduced a function `set()`. This is a key feature for websockets support, because before there was no way update the seat map once created. 

> How can i reach you personally?

My mail is public on my profile.
