### ISSUE TITLE
change seat Ids

### ISSUE THREAD

**Issue by AutomataVM** [OmarMahili/SeatchartJS#34]
Hello! I am looking is there is any way to change the Ids of the seats from colrow to a fixed number. The way I am using the map I require to have the fixed nuumber as the seat they send to me.

Thank you.

**Comment by omahili** [comment]
Hi! The seat index used by the library is already a "fixed number". This is how the index is calculated given a row and column (both 0-based):

`Seat Index = Total Columns * Row + Column`

**Comment by AutomataVM** [comment]
Thank you! That will be useful. I also need to change the name of the seats, like A1, A2 to a fixed nomeration for the maps my work uses. Guess I'll need to assign via database or something like that.

**Comment by omahili** [comment]
To change seat names you can use [`seatNameCallback`](https://seatchart.js.org/api.html#seatNameCallback).

**Comment by ttimot24** [comment]
@omahili I can't find seatNameCallback in the repo. Is this really exists?

**Comment by omahili** [comment]
@ttimot24 No not anymore, but you can use the label options. Check the example [here](https://github.com/omahili/seatchart.js/issues/45#issuecomment-2187316974).
