### ISSUE TITLE
ReactJS friendly

### ISSUE THREAD

**Issue by Ruitjes** [OmarMahili/SeatchartJS#36]
I was wondering if this package was also ReactJS friendly. Is there a NPM package I can use?

**Comment by omahili** [comment]
I think that it is possible to create a react "wrapper" around it. Basically you would need to initialize a new instance of Seatchart when the component mounts and use the component props as options. Something like:

```typescript
interface SeatchartProps {
   // options as props
}

const Seatchart: React.FC<SeatchartProps> = (props) => {
   const seatchartRef = useRef();

   useEffect(() => {
       seatchartRef.current = new Seatchart(options); // props or props.options, your choice
   }, []);

   return (
      <div id={options.map.id}>

      </div>
   );
}
```

Then you could also expose the Seatchart instance as a ref with `useImperativeHandle` and use its functions. Not perfect, but still usable.

I did not publish it as npm package, but I'm willing to do it in the next weeks. For now you can clone the repo and use it.

**Comment by Ruitjes** [comment]
@omahili Thanks for your fast response!

Seems promising, I will give it a shot in the upcoming weeks! :)

**Comment by omahili** [comment]
You're welcome 😄! 

> I did not publish it as npm package, but I'm willing to do it in the next weeks. For now you can clone the repo and use it.

To be clearer, I meant the following repo, not a specific package for react. But I'm definitely going to test the idea above and eventually include a react example in the docs, for reference.

**Comment by omahili** [comment]
The package was published to npm and now you can find a React example in the README of the project 😄

**Comment by Ruitjes** [comment]
Legend, thanks! :)
