### ISSUE TITLE
multiple maps

### ISSUE THREAD

**Issue by AutomataVM** [OmarMahili/SeatchartJS#43]
Hello! I wanted to know if it was possible to add more than one kind of map in the same page. Currently I have each map identified with a unique id, but after getting the map data only the last map appears, the other two appear empty in the div.  This is the data I have stored in an objetct to display the map.

**Comment by AutomataVM** [comment]
Edit: did it! but when the second one is being rendered, it messes up the first one! 
![image](https://user-images.githubusercontent.com/7575105/157788384-7a74852d-eed4-4180-91b8-cedc64397726.png)
any tips I could use? One thing I noticed is that the sc is used to draw the map. Is it possible to have more sc per page? one per each map I need.

**Comment by omahili** [comment]
Hi @juanpablo64 

>  but when the second one is being rendered, it messes up the first one! any tips I could use?

In which way does it mess up the first one? If you mean the positioning, you probably just need to style the containers into which you're rendering your maps. With flexbox it should be relatively easy.

> Is it possible to have more sc per page?

Yes, there's no problem in creating multiple instances of Seatchart.

**Comment by AutomataVM** [comment]
the first one has the color of the seats changed. The correct map should have the first two rows colored from columns 25 to 28. When the second map is loaded the first map is messed around. Here's the funciton that draws the maps:

``` 
async function mapDrawRecursive(map){

await $.ajax({
                method  : 'POST',
                url     : `${FOLDERADD}Aperturesite/getMapConfig`,
                data    : {'mapId': map.mapId},
                dataType: 'JSON'
            }).done(function(dataPost) {
...

let mapDrawData = {
                        map: {
                            id: "map-container-"+map.mapId,
                            reserved: {
                                seats: []
                            },
                            disabled: {
                                seats: [],
                                rows: [],
                                columns: []
                            }
                        },
                        cart:{
                            height: "20",
                            width : "20",
                        },
                        types: [
                        { type: "asignados", backgroundColor: "#a3a2a2", price:10, selected:[]},
                        { type: "disponible", backgroundColor: "#00FF00", price:10 ,selected:[]},
                        { type: "teamleader", backgroundColor: "#00FFFF", price: 10 ,selected:[]},
                        { type: "supervisor", backgroundColor: "#FFFF00", price: 10 ,selected:[]},
                        { type: "pecera", backgroundColor: "#D6CE96", price:10, selected:[]},
                        { type: "columna", backgroundColor: "#666666", price:10, selected:[]},
                        { type: "sr", backgroundColor: "#FFA136", price:10, selected:[]}
                        ]};

mapDrawData.map.rows = dataPost.rows.split(",");
mapDrawData.map.columns = dataPost.columns.split(",");
mapDrawData.map.disabled.seats = dataPost.disabled_seats.split(",");
 mapDrawData.map.disabled.rows = dataPost.disabled_rows != null ? dataPost.disabled_rows.split(",") : [];
 mapDrawData.map.disabled.columns = dataPost.disabled_columns != null ? dataPost.disabled_columns.split(",").map(e=>{ return parseInt(e,10)}) : [];
 mapDrawData.types[0].selected = assigned;
mapDrawData.types[1].selected = disponible;
mapDrawData.types[2].selected = teamleader;
mapDrawData.types[3].selected = supervisor;
 mapDrawData.types[4].selected = dataPost.pecera     != null ? dataPost.pecera.split(",") : [];
mapDrawData.types[5].selected = dataPost.columna    != null ? dataPost.columna.split(",") : [];
 let sc = new Seatchart(mapDrawData);
}
            }); 
        }
```
I obtain the map data from an ajax (datapost) and draw it with tje new SeatChart(). Each draw is done synchronic using async await

**Comment by AutomataVM** [comment]
The problem is, every time  let sc = new Seatchart(mapDrawData); the previous map data gets overwritten or something. I have checked the calls and it happens right after creating the Seatchart element. How can I create multiple, different SeatChart objects in the same page?

**Comment by AutomataVM** [comment]
I have a question about this? when you say it's posible to have multiple maps, it's with the 0.1.0 release? Because I am working with an older code, and I am pretty sure the problem lies in there. Been debugging for days and the maps keeps getting corrupted.

**Comment by omahili** [comment]
Yes, it should still work. Are you sharing options between maps? If so try by deep cloning the object before passing it to other maps.

**Comment by AutomataVM** [comment]
nope, I actually didn't want to share any options between maps! I used Object.assign to that end. Here's a little map I made, with the results on the image:


                    let map_config_data = Object.assign(res.data),
                    map_options = Object.assign({
                        map     : {},
                        types   : {},
                    });

                    map_options.map.id      = `map-container-${mapId}`;
                    map_options.map.rows    =  (mapId === '4')? 5 : 10;
                    map_options.map.columns =  (mapId === '4')? 5 : 10;

                    map_options.map.front = {
                        visible: false,
                    };

                    map_options.map.disabled = {
                       seats:    [],//(mapId === '4')? [2,3,4,5] : [12,13,14,15],
                        rows:     (mapId === '4')? [0] : [1],
                        columns:  (mapId === '4')? [0] : [1],
                    }

                    map_options.map.cart = {
                        height: "15",
                        width : "15",
                    }
var sc = new Seatchart(map_options);

![image](https://user-images.githubusercontent.com/7575105/161467569-c699823e-c9b3-494f-b1a7-bff3934e45ca.png)
I use a for to make each map, this is what is inside the for.
