### ISSUE TITLE
Indexing columns and rows

### ISSUE THREAD

**Issue by ThomasMPfeiffer** [OmarMahili/SeatchartJS#45]
Hello,
I have a question concerning the indexing of the rows and columns of the seatmap. For useage with flight seatmaps, I wanted to label the columns alphabetically and the rows numeric. Basically switching arount the default. I recognized the map options "indexerRows" and "indexerColumns". Are they ment for labeling the columns and rows? If yes, how are they used? I didn´t realy get them to work.
![Seatmap](https://user-images.githubusercontent.com/64791171/170893315-e5bc8453-2d8d-4987-a6f6-d0e67187b78e.PNG)

I hope you can help me
Kind regards
Thomas Pfeiffer

**Comment by ttimot24** [comment]
I'm also interested in this one. Did you find a solution?

**Comment by Rikj000** [comment]
Simple usage example for numeric rows + columns,   
alter `getRowLabel()` and `getColumnLabel()` as desired:
```js
// ...

function getRowLabel(row) { return (row + 1).toString(); }

function getColumnLabel(column) {
    let spacer = (column < 9) ? '0' : '';
    return spacer + (column + 1).toString();
}

// ...

seatingUiOptions.map.indexerColumns = { label: (column) => getColumnLabel(column) };
seatingUiOptions.map.indexerRows = { label: (row) => getRowLabel(row) };

let seatchart = new Seatchart(seatingUiElement, seatingUiOptions);
```

**Comment by omahili** [comment]
Thank you @Rikj000, that is indeed the way to customize labels. For inverse labeling like:

> 1A 1B 3C ... 1Z 1AA 1AB 1AC ...
> 2A 2B 2C ... 2Z 2AA 2AB 2AC ...
> ...

you can do as follows:

```javascript
const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

function getColumnLabel(column) {
  let label = '';
  let index = column;
  
  while (index >= 0) {
    label = alphabet[index % alphabet.length] + label;
    index = Math.floor(index / alphabet.length) - 1;
  }
  
  return label;
}

function getRowLabel(row) {
  return (row + 1).toString();
}

options.map.indexerColumns = { 
  label: (column) => getColumnLabel(column),
};
options.map.indexerRows = { 
  label: (row) => getRowLabel(row),
};
```
