### ISSUE TITLE
price and currency still appear when cart visibility set to false

### ISSUE THREAD

**Issue by yudistirasd** [OmarMahili/SeatchartJS#46]
hey @omahili, you work is amazing. Thank you for creating this packages. 
i have some question,  

1. how to disable price and currency in legends? 
2. it's possible to set price based on row and col  index? 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/25135334/181045852-17031bf8-57d7-47a6-8d40-2668aaea05c4.png">

**Comment by omahili** [comment]
Hi, thank you!

1. Currently it's not possible to hide prices from the legend. You need to create your own custom legend and omit it.

2. Yes, you can set seats as you wish across the map. Add a type to `options.map.seatTypes` and populate `seats` (you can also use `seatColumns` and `seatRows`, which are better for complete columns or rows). For example:

```
seatTypes: {
   default: {
      // ...
   },
   reduced: {
      price: 10,
      label: 'Reduced',
      cssClass: 'reduced',
      seats: [
         { row: 1, col: 1 },
         // ...
      ],
   },
},
```

See the [docs](https://seatchart.js.org/interfaces/SeatType.html), for more details.

**Comment by yudistirasd** [comment]
Solved, thank youu @omahili  
![Screenshot_20220804_222224](https://user-images.githubusercontent.com/25135334/182887128-74a1e999-b88b-4aaf-a3ea-95bc8e4215c8.jpg)
