### ISSUE TITLE
limit seat selection

### ISSUE THREAD

**Issue by joankent** [OmarMahili/SeatchartJS#51]
Is there a way to limit the selection of seats? That is, when you select a seat it is marked as selected, but if you select another seat, the previous seat will be automatically deselected.

**Comment by omahili** [comment]
Yes, you can listen to the `seatchange` event and then use the `setSeat` function, for example:

```javascript
const sc = new Seatchart(element, options);
sc.addEventListener('seatchange',` function handleSeatchange(e) {
   sc.setSeat({ row: 0, col: 5 }, { state: 'available' });
});
```
